### ISSUE TITLE
This error has occurred.  "ModuleNotFoundError: No module named 'pytest'"

### ISSUE THREAD

**Issue by jilianwang-meta** [shailja-thakur/CodeGen-Fine-Tuning-#5]
Traceback (most recent call last):
  File "/wjl/transformers/examples/pytorch/language-modeling/run_clm.py", line 51, in <module>
    from transformers.testing_utils import CaptureLogger
  File "/wjl/tutorial-env/lib/python3.10/site-packages/transformers/testing_utils.py", line 39, in <module>
    from pytest.doctest import (
ModuleNotFoundError: No module named 'pytest'
Traceback (most recent call last):
  File "/wjl/transformers/examples/pytorch/language-modeling/run_clm.py", line 51, in <module>
    from transformers.testing_utils import CaptureLogger
  File "/wjl/tutorial-env/lib/python3.10/site-packages/transformers/testing_utils.py", line 39, in <module>
    from pytest.doctest import (
ModuleNotFoundError: No module named 'pytest'

**Comment by jilianwang-meta** [comment]
Have you ever encountered such a mistake? How did you solve it?

**Comment by foundten** [comment]
try, `pip install pytest`.
